### ISSUE TITLE
Deployment packaging

### ISSUE THREAD

**Issue by pit-bob** [ai-ro-bo/Rox.Camera.Provider.Xamarin#20]
Fix some deployment packing items.
* NuGet ```<authors>``` try using @ mention, and make sure it isn't deprecated.
* NuGet tags to be refreshed.
* Create GitHub tags.
* GitHub banner with Xamarin logo.
* NuGet readme has extra break lines.
* GitHub readme.md should be as NuGet readme.md and NuGet readme.md can be simplified.
* Restructure Release Notes.

**Comment by pit-bob** [comment]
I created a GitHub Page for the repository, in a new environment, but it has been deleted as I think the readme.md will more productive at the repository level.

In the future I will create a GitHub page for the organization @ai-ro-bo , and possibly a personal page for @r-o-d-p .

**Comment by pit-bob** [comment]
I have set up some sites, no content at this stage, here are the test links:

https://airobo.software/test-link/

**Comment by r-o-d-p** [comment]
I am about to create 5.0.0-pre2, are NuGet images ready?

I will put this pre-release through anyway some time tomorrow, even without correct images.

**Comment by pit-bob** [comment]
I am still working with the SVG's, so I may have something to you tomorrow.

**Comment by r-o-d-p** [comment]
Updated version, readme, and nuspec.

**Comment by r-o-d-p** [comment]
I still have the new images to incorporate.
